config/routes.rb
Rails.application.routes.draw do
  get 'replies/create'
  get 'replies/destroy'
  get 'sessions/new', to: 'sessions#new'
  post 'sessions/new', to: 'sessions#create'
  get 'sessions/destroy', to: 'sessions#destroy'
  get '/users/new', to: 'users#new'
  post '/users/new', to: 'users#create'
  get '/users/:id', to: "users#show"
  get '/users/:id/edit', to: 'users#edit'
  patch '/users/:id', to: 'users#update'
  get 'messages/index', to: 'messages#index'
  get 'messages/new', to: 'messages#new'
  post '/messages/new', to: 'messages#create'
  get '/messages/:id', to: 'messages#show'
  get '/articles', to: 'articles#index'
  root to: 'articles#index'
  resources :messages do
    resources :replies
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :replies
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :messages
  has_many :replies
  
  validates :username, uniqueness: true
  validates :email, uniqueness: true
  #validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :login, :logout

  def login
    session[:user_id] = @user.id
    session[:username] = session_params[:username]
  end

  def logout
    session.clear
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def create
    @user = User.find(session[:user_id])
    @message = @user.messages.create(message_params)

    if @message.save!
      redirect_to '/messages/index', notice: "Question posted"
    else
      redirect_to '/messages/index', notice: "Please try to post again"
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])

    if @message.update(message_params)
      redirect_to '/messages/index', notice: "Successfully Updated"
    else
      render :edit, notice: "Please try again"
    end
  end

  def destroy
    @message = Message.find(params[:id])
    if @message.destroy
      redirect_to '/messages/index', notice: "Successfully Deleted"
    else
      redirect_to '/messages/index', notice: "Please try again"
    end
  end

  private

  def message_params
    params.permit(:title, :body)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    reply_params
    @reply = Reply.create(user_id: session[:user_id], message_id: @message, body: @body)

    if @reply.save!
      redirect_to "/messages/#{@message}", notice: "Answer posted"
    else
      redirect_to "/messages/#{@message}", notice: "Please try to post again"
    end
  end

  def destroy
  end

  private

  def reply_params
    @message = params[:message_id]
    @body = params[:reply][:body]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: session_params[:username])

    if @user == nil
      redirect_to '/sessions/new', notice: "Incorrect username"
    elsif @user.authenticate(session_params[:password]) == false
      redirect_to '/sessions/new', notice: "Incorrect password"
    else
      login
      redirect_to '/', notice: "Successfully logged in"
    end
  end

  def destroy
    logout
    redirect_to '/', notice: "Successfully logged out"
  end

  private

  def session_params
    params.permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create

    @user = User.new(user_params)

    if @user.errors.present?
      redirect_to '/users/new', notice: "Please check each field is correctly filled in"
    elsif @user.save
      redirect_to '/articles', notice: "User created"
    else
      redirect_to '/users/new', notice: "Ensure username and email address are unique and that passwords match"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to '/', notice: "Successfully Updated"
    else
      render :edit, notice: "Please try again"
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  private

  def user_params
    params.permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/index.html.erb
<h1><a href="/"> Parrot Pandemonium </a></h1>
<% if flash[:notice] %>
  <%=flash[:notice] %><br>
<% end %>
<% if !!session[:username] %>
  Welcome, <%= session[:username] %><br>
  <a href="/users/<%=session[:user_id]%>">Update Details</a><br>
  <a href = "/sessions/destroy"> Logout </a>
<% else %>
  <a href = "/users/new"> Create User </a><br>
  <a href = "/sessions/new"> Login </a><br>
<% end %>

<h2>A list of Articles</h2>
<ul>
  <li>Commonly kept parrots</li>
  <li>Basic Set Up</li>
</ul>

<h2><a href = "/messages/index"> Q & A </a></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParrotPandemonium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
  <%= form_with model: message do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  <% end %>

app/views/messages/edit.html.erb
<h1><a href="/"> Parrot Pandemonium </a></h1>

<h2>Q & A</h2><% if session[:user_id] == @message.user_id %>
  Welcome, <%= session[:username] %><br>
  Edit Question:

  <%= render "form", message: @message %>

<% else %>

  Only the author of the question, when logged in, can edit the question.<br>
  <a href = "/sessions/new"> Login </a><br>
<% end %>

app/views/messages/index.html.erb
<h1><a href="/"> Parrot Pandemonium </a></h1>

<h2>Q & A</h2>
<% if flash[:notice] %>
  <%=flash[:notice] %><br>
<% end %>
<% if !!session[:username] %>
  Welcome, <%= session[:username] %><br>

  <a href = "/messages/new"> Post a question </a><br>
<% else %>
  <a href = "/sessions/new"> Login </a><br>
<% end %>

<h1> Questions </h1>
<ul>
  <% @messages.reverse.each do |message| %>
    <li>
      <% user = User.find_by(id: message.user_id) %>
      <a href = "/messages/<%= message.id %>">
        <%= message.title %>
      </a><br>
      by <%= user.username %> on <%= message.created_at %><br>
      <%= message.body %><br>
    </li>
  <% end %>
</ul>

app/views/messages/new.html.erb
<h1><a href="/"> Parrot Pandemonium </a></h1>

<h2>Q & A</h2><% if !!session[:username] %>
  Welcome, <%= session[:username] %><br>
  Post a question:
  <%= form_with model: @message do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  <% end %>
<% else %>
  <a href = "/sessions/new"> Login </a><br>
<% end %>

app/views/messages/show.html.erb
<h1><a href="/"> Parrot Pandemonium </a></h1>

<h2>Q & A</h2>
<% if flash[:notice] %>
  <%=flash[:notice] %><br>
<% end %>
<% if !!session[:username] %>
  Welcome, <%= session[:username] %><br>

  <a href = "/messages/new"> Post a question </a><br>
<% else %>
  <a href = "/sessions/new"> Login </a><br>
<% end %>

<% user = User.find_by(id: @message.user_id) %>
  <h2><%= @message.title %></h2>
<br>
<p>by <b><%= user.username %></b> on <%= @message.created_at %></p>
<p><%= @message.body %></p>
<% if session[:user_id] == @message.user_id %>
  <%= link_to 'Edit Question', edit_message_path(@message)%><br>
  <%= link_to 'Delete', message_path(@message),
                        method: :delete,
                        data: { confirm: "Are you sure you wish to delete this question?" }%>
<% end %>

<h3> Answers </h3>

<% @message.replies.reverse.each do |reply| %>
  <p>
    <% user = User.find_by(id: reply.user_id) %>
    <p><b><%= user.username %></b> said:</p>
      <%= reply.body %><br>
      on: <%= reply.created_at %><br><br>
<% end %>



<%= form_with model: [@message, @message.replies.build] do |form| %>
  <div>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/replies/create.html.erb
<h1>Replies#create</h1>
<p>Find me in app/views/replies/create.html.erb</p>

app/views/replies/destroy.html.erb
<h1>Replies#destroy</h1>
<p>Find me in app/views/replies/destroy.html.erb</p>

app/views/replies/show.html.erb
<h1>Q & A</h1>
<% if flash[:notice] %>
  <%=flash[:notice] %><br>
<% end %>
<% if !!session[:username] %>
  Welcome, <%= session[:username] %><br>
<% else %>
  <a href = "/sessions/new"> Login </a><br>
<% end %>
<h1> <%= @message.title %></h1>
<% user = User.find_by(id: @message.user_id) %>
by <%= user.username %> on <%= @message.created_at %><br>
<%= @message.body %>
<h2> Answers </h2>
<% @message.replies.each do |reply| %>
  <p>
  <% user = User.find_by(id: reply.user_id) %>
    <b><%= user %></b> said:
    <%= reply.body %><br>
    at <%= reply.created_at %><br>
  </p>
<% end %>

<h2> Add Answer </h2>
<%= form_with model: [ @message, @message.replies.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>




<h1> Questions </h1>
<ul>
  <% @messages.each do |message| %>
    <li>
      <% user = User.find_by(id: message.user_id) %>
      <a href = "/messages/<%=message.id%>">
        <%= message.title %>
      </a><br>
      by <%= user.username %> on <%= message.created_at %><br>
      <%= message.body %>
    </li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><a href="/"> Parrot Pandemonium </a></h1>

<h2>Update Details</h2>
<% if flash[:notice] %>
  <%=flash[:notice] %><br>
<% end %>
<%= render "form", user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>
<% if flash[:notice] %>
  <%=flash[:notice] %><br>
<% end %>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><a href="/"> Parrot Pandemonium </a></h1>

<h2>View Profile</h2>
<% if flash[:notice] %>
  <%=flash[:notice] %><br>
<% end %>
Username:  <%= @user.username %><br>
E-mail Address: <%= @user.email %><br>
<%= link_to 'Edit', edit_user_path(@user)%>